{% set name = "blaupause" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b02d3c39ffad3eee068d1e4720e810d4ef51d184bc99f026f7b7d7a532275775

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytest
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - blaupause
  commands:
    - python -c "import sys; import blaupause; sys.exit(blaupause.test())"

about:
  home: https://github.com/lang-m/blaupause
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A sample Python-based package that can be used as a tutorial for setting up a project.
  description: |
    A sample Python-based package that can be used as a tutorial for setting up a project.
  doc_url: https://blaupause.readthedocs.io/
  dev_url: https://github.com/lang-m/blaupause

extra:
  recipe-maintainers:
    - lang-m
    - marijanbeg
